### PR TITLE
updates ci to deploy to refapp

### PR DESCRIPTION
**Pull request by pirupius**

### CODE REVIEW

**Comment by mogoodrich** [comment]
flagging @ibacher  as I don't know enough about this stuff to review

**Comment by pirupius** [comment]
@mogoodrich i had a chat with Ian about this. The method in this PR seems to be deprecated and i made another PR to the to the ref app to resolve this https://github.com/openmrs/openmrs-distro-referenceapplication/pull/635 

I don't know if this need for this PR anymore but will wait for Ian's comment.

**Comment by ibacher** [comment]
The deploy setup should look like the one in [ESM core](https://github.com/openmrs/openmrs-esm-core/blob/a6b8eed6e4a358ec0132d616354ae40e218f58a0/.github/workflows/ci.yml#L89), i.e., to trigger building the RefApp on push.

**Comment by pirupius** [comment]
Closing this PR as it's stale and already resolved.

**Pull request closed without merging**
